# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database for NixOS stable";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/cyntheticfox/nix-index-database-stable/releases/download/2023-08-27/index-x86_64-linux";
        sha256 = "1ac8s9xpplzw5kf6mbfp51nyvayc5siz036j4y1n587zizr3g3ax";
      };
    };
}
