# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database for NixOS stable";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/cyntheticfox/nix-index-database-stable/releases/download/2023-09-03/index-x86_64-linux";
        sha256 = "098wnqbfl52mkf0cx9y83r3d9y8fg919aq3dqvz3l5wcbs67bfl6";
      };
    };
}
