# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database for NixOS stable";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/cyntheticfox/nix-index-database-stable/releases/download/2023-12-10/index-x86_64-linux";
        sha256 = "0sjngl0p7d0z1krm80v5cqn5gcljv6qyfmpk5hnf7hyaz7sbqik2";
      };
    };
}
